### ISSUE TITLE
Don't process hidden folders

### ISSUE THREAD

**Issue by Razzeee** [xbmc/addon-check#123]
We should ignore hidden folders, everything starting with `.` like `.git`

See this log for some false alarms https://travis-ci.org/trakt/script.trakt/jobs/440324400

**Comment by cybcafe** [comment]
It seems to me that there is already something that does it.

https://github.com/xbmc/addon-check/blob/4b1f534ed9fc961722c0e4c1e33538dc75de895a/kodi_addon_checker/check_repo.py#L13

When do you want to skip hidden folders ?

**Comment by Razzeee** [comment]
the log you see above is not using the `check_repo` function as it's not being run on a repo. I think it uses the other way to be run, which is via the `check_addon` module https://github.com/xbmc/addon-check/blob/master/kodi_addon_checker/check_addon.py

**Comment by cybcafe** [comment]
Okay fine I had trouble reading the logfile.

**Comment by cybcafe** [comment]
https://github.com/xbmc/addon-check/blob/master/kodi_addon_checker/handle_files.py#L33-L44

@Razzee so just a new conditional in this for loop and then appropriate tests right ?

I noticed that os.walk also returns its argument as the first element. Is it okay for the whole addon to be a hidden directory ? If so I should skip the condition on the first iteration. And if not, an error should be thrown; otherwise file_index will remain empty.

**Comment by Razzeee** [comment]
It's not okay for an addon to be in a hidden dir. 

The method you pointed out seems to be the right spot for this change. I don't think you need to throw any error, just ignore the folder.

**Comment by cybcafe** [comment]
If it’s not okay, better test for it and add an entry to the report right ?

**Comment by Razzeee** [comment]
Yeah, but maybe only on the top level?

**Comment by cybcafe** [comment]
Okay I’ll PR something on Monday.

**Comment by cybcafe** [comment]
Oh I’m sorry @mzfr I didn’t see your pr

**Comment by LordGameleo** [comment]
Is this issue open?? @Razzeee

**Comment by Razzeee** [comment]
It's not solved, but I think it might not be needed anymore

**Comment by LordGameleo** [comment]
Thanks :)
