### ISSUE TITLE
[bug] Broken addon version comparator with beta

### ISSUE THREAD

**Issue by SylvainCecchetto** [xbmc/addon-check#224]
Since some days (maybe the 0.0.17 release) the add-on version comparator is broken with beta syntax.

My local addon.xml is `0.2.19~beta01` but I get a `ERROR: plugin.video.catchuptvandmore addon already exist with a higher version: 0.2.18 in krypton branch`.

This bug was not here before (at least, it worked with kodi-addon-checker 0.0.16)

**Comment by Razzeee** [comment]
https://github.com/xbmc/addon-check/pull/216

**Comment by enen92** [comment]
Thanks for reporting @SylvainCecchetto 

Problem is that `0.2.19~beta01` is not PEP404 compliant, hence the `packaging.version.parse` function parses it as a `packaging.version.LegacyVersion` object instead of a `packaging.version.Version` object. `LegacyVersion` is always lower than `Version` no matter what.

I gave this a test with the Kodi internal versioning system and your version is in fact higher than `0.2.18`, so the addon checker should mimic the kodi behaviour.

I'll try to come up with a fix asap.
