### ISSUE TITLE
Check complexity of addon entrypoints

### ISSUE THREAD

**Issue by enen92** [xbmc/addon-check#68]
It is a general good practice to keep the entrypoints (the python files refered in addon.xml) to a minimum since they won't get compiled to bytecode. Usually the entrypoint should be something as simpler as:

```python
import resources.lib.plugin

plugin.run()
```

While the main plugin code is kept in a module.
The `addon-check-tool` could somehow check the complexity of the entrypoint and might suggest the author to improve the addon performance by pointing to an example. A few possibilities:

1) Just check the number of uncommented lines in the entrypoint file and decide if it is lower than, lets say, 10 lines?

2) Check the number of imports on the entrypoint? This probably means the main plugin logic is executed there or, at least, there is room for improvement

3) Something more complex by exploiting cyclomatic complexity? Might be too hard to accomplish.

4) Infer from the number of python files in the addon that are not the entrypoint. This can lead to a lot of false positives though.

Option 1) seems the easiest one to implement if reforced by a few more checks

**Comment by mzfr** [comment]
This can be a good thing to do.
1. This is easy to implement but we have to decide the number of line we want to check. Maybe we can check number of line in entrypoint files for some famous addons like [plugin.video.youtube](https://github.com/jdf76/plugin.video.youtube)(it have 7 lines in its entrypoint file).

2. Instead of this one I think 1 is better.
3. What do you mean by "exploiting" CC ?
4. Definitely not a good way to do it because if we look into our example in option 1 then that addon have lots of py files so this will actually result in false warnings something like `You have lots of py files in your addon ` which is a very vague warning but instead of that something like  `your entry point file is too complex. Please Try to improve it ` is a better warning because is actually pin points to the problem.

I think maybe we can discuss option 1 and 3 and see which one will bring a better result.

**Comment by mzfr** [comment]
@enen92 Ok so option 3 is actually one of task of GSoC '18. I have a post on kodi forum about the task so  If you want you can see [this](https://forum.kodi.tv/showthread.php?tid=328798&highlight=gsoc)
So maybe we can just leave this till then or try to do it with option 1 ?

**Comment by enen92** [comment]
Sure thing. Option 1 seems the way to go for a quick prototype

**Comment by mzfr** [comment]
ok I'll try it.

**Comment by enen92** [comment]
1. Don't hardcode the number of lines, make it configurable in the tool configuration file
2. You have to grab the entrypoints from addon.xml. And this is not so trivial as it sounds. Note that:
- this issue affects both plugins and scripts
- an addon can have multiple entry points (one for each extension point). For instance an addon can be a script (program.addon) and also a service and also define a context menu item.
- multiple extension points may have the same entrypoint so it is not needed to check the same file twice
3. Yes. However note that in this case the addon is only a plugin (`xbmc.python.pluginsource`). Probably you should start by listing all the possible extension points (plugin, script, service, contextmenu)

**Comment by mzfr** [comment]
1. Ok I'll make it configurable via config file or should I add this as an CLI argument ? 
2. ok I'll Do that 
3. ok so for example [Twitch](https://github.com/MrSprigster/Twitch-on-Kodi/blob/master/addon.xml) addon have multiple extension so should I run this check for all the extensions ?

**Comment by enen92** [comment]
1. I think the granularity of this setting is so low it does not make sense to pass it as a CLI argument. Maybe having it as a variable in a configuration file is better

3. Yes. Ideally first you should investigate which extension points do exist that have a python file entrypoint. IIRC those are: `xbmc.python.pluginsource`, `xbmc.python.script`, `kodi.context.item`, `xbmc.service`. 

However there are a few more that might take advantage of this checking method:

```
"xbmc.python.weather"     Used for weather scripts
"xbmc.python.subtitles"    Used for subtitle scripts
"xbmc.python.lyrics"         Used for lyrics scripts
"xbmc.python.library"       Used for skin dependent scripts (e.g. recently added script). Input from one of the skinners might be valuable here
```
